In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
data = {'year' : [
    2010, 2011, 2012, 2010, 2011, 2012, 2010, 2011, 2012
],
'team' : [
    'FCBarcelona', 'FCBarcelona', 'FCBarcelona',
    'RMadrid', 'RMadrid', 'RMadrid',
    'ValenciaCF', 'ValenciaCF', 'ValenciaCF'
],
'wins': [30, 28, 32, 29, 32, 26, 21, 17, 19],
'draws': [6, 7, 4, 5, 4, 7, 8, 10, 8],
'loses': [2, 3, 2, 4, 2, 5, 9, 11, 11]
}
football = pd.DataFrame(data, columns=['year', 'team', 'wins', 'draws', 'loses'])
football

   year         team  wins  draws  loses
0  2010  FCBarcelona    30      6      2
1  2011  FCBarcelona    28      7      3
2  2012  FCBarcelona    32      4      2
3  2010      RMadrid    29      5      4
4  2011      RMadrid    32      4      2
5  2012      RMadrid    26      7      5
6  2010   ValenciaCF    21      8      9
7  2011   ValenciaCF    17     10     11
8  2012   ValenciaCF    19      8     11

In [26]:
edu = pd.read_csv('educ_figdp_1_Data.csv', na_values=':', usecols=["TIME", "GEO", "Value"])
print(edu)

     TIME                            GEO  Value
0    2000  European Union (28 countries)    NaN
1    2001  European Union (28 countries)    NaN
2    2002  European Union (28 countries)   5.00
3    2003  European Union (28 countries)   5.03
4    2004  European Union (28 countries)   4.95
..    ...                            ...    ...
379  2007                        Finland   5.90
380  2008                        Finland   6.10
381  2009                        Finland   6.81
382  2010                        Finland   6.85
383  2011                        Finland   6.76

[384 rows x 3 columns]

In [7]:
edu.head ()

   TIME                            GEO  Value
0  2000  European Union (28 countries)    NaN
1  2001  European Union (28 countries)    NaN
2  2002  European Union (28 countries)   5.00
3  2003  European Union (28 countries)   5.03
4  2004  European Union (28 countries)   4.95

In [8]:
edu.tail()

     TIME      GEO  Value
379  2007  Finland   5.90
380  2008  Finland   6.10
381  2009  Finland   6.81
382  2010  Finland   6.85
383  2011  Finland   6.76

In [9]:
edu.describe()

              TIME       Value
count   384.000000  361.000000
mean   2005.500000    5.203989
std       3.456556    1.021694
min    2000.000000    2.880000
25%    2002.750000    4.620000
50%    2005.500000    5.060000
75%    2008.250000    5.660000
max    2011.000000    8.810000

In [10]:
edu ['Value']

0       NaN
1       NaN
2      5.00
3      5.03
4      4.95
       ...
379    5.90
380    6.10
381    6.81
382    6.85
383    6.76
Name: Value, Length: 384, dtype: float64

In [11]:
edu ['TIME']

0      2000
1      2001
2      2002
3      2003
4      2004
       ...
379    2007
380    2008
381    2009
382    2010
383    2011
Name: TIME, Length: 384, dtype: int64

In [31]:
edu [10:14]

    TIME                            GEO  Value
10  2010  European Union (28 countries)   5.41
11  2011  European Union (28 countries)   5.25
12  2000  European Union (27 countries)   4.91
13  2001  European Union (27 countries)   4.99

In [34]:
edu.loc[90:94, ['TIME', 'GEO']]

    TIME      GEO
90  2006  Belgium
91  2007  Belgium
92  2008  Belgium
93  2009  Belgium
94  2010  Belgium

In [35]:
edu[edu['Value'] > 6.5].tail()

     TIME      GEO  Value
286  2010    Malta   6.74
287  2011    Malta   7.96
381  2009  Finland   6.81
382  2010  Finland   6.85
383  2011  Finland   6.76

In [12]:
edu[edu['Value'].isnull()].head()

    TIME                            GEO  Value
0   2000  European Union (28 countries)    NaN
1   2001  European Union (28 countries)    NaN
36  2000       Euro area (18 countries)    NaN
37  2001       Euro area (18 countries)    NaN
48  2000       Euro area (17 countries)    NaN

In [13]:
edu.max(axis= 0)

TIME      2011
GEO      Spain
Value     8.81
dtype: object

In [16]:
print ("Pandas max function:", edu['Value'].max())
print ("Python max function:", max(edu['Value']))

Pandas max function: 8.81
Python max function: nan

In [17]:
s = edu["Value"]/100
s.head()

0       NaN
1       NaN
2    0.0500
3    0.0503
4    0.0495
Name: Value, dtype: float64

In [18]:
s = edu ["Value"].apply(np.sqrt)
s.head()

0         NaN
1         NaN
2    2.236068
3    2.242766
4    2.224860
Name: Value, dtype: float64

In [19]:
s = edu["Value"].apply(lambda d: d**2)
s.head()

0        NaN
1        NaN
2    25.0000
3    25.3009
4    24.5025
Name: Value, dtype: float64

In [36]:
edu['ValueNorm'] = edu['Value']/edu['Value'].max()
edu.tail()

     TIME      GEO  Value  ValueNorm
379  2007  Finland   5.90   0.669694
380  2008  Finland   6.10   0.692395
381  2009  Finland   6.81   0.772985
382  2010  Finland   6.85   0.777526
383  2011  Finland   6.76   0.767310

In [38]:
edu.drop('ValueNorm', axis = 1, inplace = True)
edu.head()

   TIME                            GEO  Value
0  2000  European Union (28 countries)    NaN
1  2001  European Union (28 countries)    NaN
2  2002  European Union (28 countries)   5.00
3  2003  European Union (28 countries)   5.03
4  2004  European Union (28 countries)   4.95

In [43]:
edu = pd.concat([edu, pd.DataFrame({"TIME": [2000], "Value": [5.00], "GEO": ['a']})], ignore_index=True)
edu.tail()

     TIME      GEO  Value
380  2008  Finland   6.10
381  2009  Finland   6.81
382  2010  Finland   6.85
383  2011  Finland   6.76
384  2000        a   5.00

In [44]:
edu.drop(max(edu.index), axis = 0, inplace = True)
edu.tail()

     TIME      GEO  Value
379  2007  Finland   5.90
380  2008  Finland   6.10
381  2009  Finland   6.81
382  2010  Finland   6.85
383  2011  Finland   6.76

In [46]:
eduDrop = edu.drop(edu[edu["Value"].isnull()].index)
eduDrop.head()

   TIME                            GEO  Value
2  2002  European Union (28 countries)   5.00
3  2003  European Union (28 countries)   5.03
4  2004  European Union (28 countries)   4.95
5  2005  European Union (28 countries)   4.92
6  2006  European Union (28 countries)   4.91